/* Generated by AN DISI Unibo */ 
package it.unibo.datacleaner

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import java.io.*

class Datacleaner ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				var firstInit = true
				var p: Process = Runtime.getRuntime().exec(".\\sonar_sim_dev.bat") //DA CAMBIARE
				var reader: BufferedReader = BufferedReader(  InputStreamReader(p.getInputStream() ))
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("datacleaner | starts")
						
									if(firstInit){
										firstInit = false
									}
									else{
										p = Runtime.getRuntime().exec(".\\sonar_sim_dev.bat") //DA CAMBIARE
										reader = BufferedReader(  InputStreamReader(p.getInputStream() ))
									}
									
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="read", cond=doswitch() )
				}	 
				state("read") { //this:State
					action { //it:State
						
									var data = reader.readLine()
									//println("sonarHCSR04Support data = $data"   )
									if( data != null ){
										try{ 
											val v = data.toInt()
						
											val m1 = "distance(${v})"
											val event = MsgUtil.buildEvent("datacleaner", "sonardata", m1)
											//println(event)
											emitLocalStreamEvent( event )	
											
											
										}catch(e: Exception){
											println("sonarHCSR04Support doRead ERROR: $e "   )
										}
									}	
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_read", 
				 	 					  scope, context!!, "local_tout_"+name+"_read", 1000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="read",cond=whenTimeout("local_tout_"+name+"_read"))   
					transition(edgeName="t01",targetState="stopped",cond=whenDispatch("sonarstop"))
				}	 
				state("stopped") { //this:State
					action { //it:State
						
									reader.close()
									p.destroy()
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="s0",cond=whenDispatch("sonarstart"))
				}	 
			}
		}
} 
